apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-node-exporter-ta
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/metrics
    - services
    - endpoints
    - pods
    - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
    - probes
    - scrapeconfigs
    - servicemonitors
    - podmonitors
    verbs: ["*"]
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
