{{- if .Values.hmc.installTemplates }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: motel-child
  namespace: hmc-system
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  chart: motel-child
  interval: 10m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: motel
  version: 0.1.2
{{- end }}
