{{- if .Values.hmc.installTemplates }}
apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: motel-child-0-1-2
  namespace: hmc-system
spec:
  helm:
    chartRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: motel-child
      namespace: hmc-system
    chartVersion: 0.1.2
  providers: []
{{- end }}
