apiVersion: v2
name: motel-mothership
description: A Helm chart that deploys Grafana, Promxy, and VictoriaMetrics.
version: 0.1.6
appVersion: "1.0"
dependencies:
  - name: grafana-operator
    version: v5.13.0
    repository: "oci://ghcr.io/grafana/helm-charts"
    condition: grafana.enabled
  - name: victoria-metrics-operator
    version: "0.36.*"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-operator.enabled

