global:
  clusterLabel: clusterName
  clusterName: hmc-child
prometheus-operator-crds:
  enabled: true
kube-state-metrics:
  enabled: true
victoria-metrics-operator:
  enabled: true
  crds:
    plain: true
prometheus-node-exporter:
  enabled: true
  hostNetwork: false
  service:
    labels:
      jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
opencost:
  enabled: true
  opencost:
    prometheus:
      username: "motel"
      password: "motel"
      external:
        enabled: true
        url: "https://vmauth.hmc0.example.net/vm/select/0/prometheus"
      internal:
        enabled: false
    exporter:
      defaultClusterId: "hmc-child"
      extraEnv:
        EMIT_KSM_V1_METRICS: "false"
        EMIT_KSM_V1_METRICS_ONLY: "true"
opentelemetry-operator:
  enabled: true
  manager:
    collectorImage:
      repository: "otel/opentelemetry-collector-contrib"
victoriametrics:
  enabled: true
  vmagent:
    enabled: true
    remoteWriteUrl: https://vmauth.hmc0.example.net/vm/insert/0/prometheus/api/v1/write
    remoteUsername: motel
    remotePassword: motel
fluent-bit:
  enabled: true
  outputHost: vmauth.hmc0.example.net
  outputURI: /vls/insert/jsonline
  outputUsername: motel
  outputPassword: motel
  args:
    - --workdir=/fluent-bit/etc
    - --config=/fluent-bit/etc/conf/fluent-bit.conf
    - --enable-hot-reload
  extraContainers: |
    - name: reloader
      image: {{ include "fluent-bit.image" .Values.hotReload.image }}
      args:
        - {{ printf "-webhook-url=http://localhost:%s/api/v2/reload" (toString .Values.metricsPort) }}
        - -volume-dir=/watch/config
        - -volume-dir=/watch/outputs
      volumeMounts:
        - name: config
          mountPath: /watch/config
        - name: vl-outputs
          mountPath: /watch/outputs
  daemonSetVolumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: vl-outputs
      configMap:
        name: vl-outputs
  daemonSetVolumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: vl-outputs
      mountPath: /fluent-bit/etc/conf/vl
  resources: {}
  config:
    outputs: |
      @INCLUDE /fluent-bit/etc/conf/vl/output_*.conf
    filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          Merge_Log           On
          Keep_Log            On
          K8S-Logging.Parser  On
          K8S-Logging.Exclude On
      [FILTER]
          Name         nest
          Match        *
          Wildcard     pod_name
          Operation    lift
          Nested_under kubernetes
          Add_prefix   kubernetes_
