apiVersion: v2
name: motel-collectors
description: A Helm chart that deploys OpenTelemetryCollector resources
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: prometheus-node-exporter
    version: "4.39.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled
  - name: kube-state-metrics
    version: "5.25.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
