apiVersion: v2
name: motel-operators
description: A Helm chart that deploys opentelemetry-operator and prometheus CRDs
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: opentelemetry-operator
    version: "0.75.*"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
  - name: prometheus-operator-crds
    version: "15.0.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-operator-crds.enabled
