apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: aws-storage0
  namespace: hmc-system
  labels:
    motel: "storage"
spec:
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: hmc-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: true
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
  template: aws-standalone-cp-0-0-4
  servicesPriority: 100
  services:
    - template: ingress-nginx-4-11-3
      name: ingress-nginx
      namespace: ingress-nginx
    - name: cert-manager
      namespace: cert-manager
      template: cert-manager
      values: |
        crds:
          enabled: true
    - name: motel-storage
      namespace: motel
      template: motel-storage
      values: |
        victoriametrics:
          vmauth:
            ingress:
              host: vmauth.storage0.example.net
            credentials:
              username: motel
              password: motel
        grafana:
          ingress:
            host: grafana.storage0.example.net
        cert-manager:
          email: mail@example.net
