apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: aws-managed0
  namespace: hmc-system
  labels:
    motel: "collector"
spec:
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: hmc-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: false
    region: us-east-2
    worker:
      instanceType: t3.small
    workersNumber: 3
  template: aws-standalone-cp-0-0-4
  servicesPriority: 100
  services:
    - template: cert-manager
      name: cert-manager
      namespace: motel
      values: |
        crds:
          enabled: true
    - template: motel-operators
      name: motel-operators
      namespace: motel
    - template: motel-collectors
      name: motel-collectors
      namespace: motel
      values: |
        global:
          clusterName: aws-managed0
        opencost:
          enabled: true
          prometheus:
            external:
              url: "https://vmauth.storage0.example.net/vm/select/0/prometheus"
          exporter:
            defaultClusterId: "aws-managed0"
        motel:
          logs_endpoint: https://vmauth.storage0.example.net/vls/insert/opentelemetry/v1/logs
          metrics_endpoint: https://vmauth.storage0.example.net/vm/insert/0/prometheus/api/v1/write
