{{- if index .Values "grafana" "enabled" | default false }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-vm
  labels:
    dashboards: grafana
    namespace: {{ .Release.Namespace }}
spec:
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Mi
  deployment:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 472
          initContainers:
            - name: "load-vm-ds-plugin"
              image: "curlimages/curl:latest"
              command: [ "/bin/sh" ]
              workingDir: "/var/lib/grafana"
              securityContext:
                runAsUser: 472
                runAsNonRoot: true
                runAsGroup: 472
              args:
                - "-c"
                - |
                  set -ex
                  mkdir -p /var/lib/grafana/plugins/
                  ver=$(curl -s https://api.github.com/repos/VictoriaMetrics/victoriametrics-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
                  curl -L https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/$ver/victoriametrics-datasource-$ver.tar.gz -o /var/lib/grafana/plugins/vm-plugin.tar.gz
                  vlver=$(curl -s https://api.github.com/repos/VictoriaMetrics/victorialogs-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
                  curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/$vlver/victoriametrics-logs-datasource-$vlver.tar.gz -o /var/lib/grafana/plugins/vl-plugin.tar.gz
                  tar -xf /var/lib/grafana/plugins/vl-plugin.tar.gz -C /var/lib/grafana/plugins/
                  tar -xf /var/lib/grafana/plugins/vm-plugin.tar.gz -C /var/lib/grafana/plugins/
                  rm /var/lib/grafana/plugins/vm-plugin.tar.gz
              volumeMounts:
                - name: grafana-data
                  mountPath: /var/lib/grafana
          volumes:
          - name: grafana-data
            persistentVolumeClaim:
              claimName: grafana-vm-pvc
  config:
    plugins:
      allow_loading_unsigned_plugins: victoriametrics-datasource,victoriametrics-logs-datasource
    security:
      admin_user: {{ .Values.grafana.security.admin_user | quote }}
      admin_password: {{ .Values.grafana.security.admin_password | quote }}
{{- if .Values.grafana.ingress.enabled }}
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/tls-acme: "true"
    spec:
      ingressClassName: nginx
      rules:
        - host: {{ .Values.grafana.ingress.host | quote }}
          http:
            paths:
              - backend:
                  service:
                    name: grafana-vm-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - {{ .Values.grafana.ingress.host | quote }}
          secretName: grafana-cluster-tls
{{- end }}
{{- end }}
