{{- if (index .Values "victoriametrics" "vmagent" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  externalLabels:
    clusterName: {{ .Values.global.clusterName }}
  extraArgs:
    promscrape.dropOriginalLabels: "true"
    promscrape.streamParse: "true"
  image:
    tag: v1.105.0
  license: {}
  port: "8429"
  remoteWrite:
  - url: {{ .Values.victoriametrics.vmagent.remoteWriteUrl | quote }}
    basicAuth:
      username:
        key: username
        name: vmauth-creds
      password:
        key: password
        name: vmauth-creds
  scrapeInterval: 20s
  selectAllByDefault: true
{{- if .Values.opencost.enabled | default false }}
  inlineScrapeConfig: |
    - job_name: opencost
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
      - names:
        - motel-child-opencost.motel-child
        type: 'A'
        port: 9003
{{- end }}
{{- end }}
