{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmcluster.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  license: {}
  replicationFactor: {{ .Values.victoriametrics.vmcluster.replicationFactor | default 2 }}
  retentionPeriod: "1"
  vminsert:
    extraArgs: {}
    image:
      tag: v1.105.0-cluster
    port: "8480"
    replicaCount: {{ .Values.victoriametrics.vmcluster.replicaCount | default 3 }}
  vmselect:
    cacheMountPath: /select-cache
    extraArgs:
      vmalert.proxyURL: http://vmalert-cluster.{{ .Release.Namespace }}.svc:8080/
    image:
      tag: v1.105.0-cluster
    port: "8481"
    replicaCount: {{ .Values.victoriametrics.vmcluster.replicaCount | default 3 }}
    resources: {}
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
          storageClassName: {{ .Values.global.storageClass }}
  vmstorage:
    image:
      tag: v1.105.0-cluster
    replicaCount: {{ .Values.victoriametrics.vmcluster.replicaCount | default 3 }}
    resources: {}
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: {{ .Values.global.storageClass }}
    storageDataPath: /vm-data
{{- end }}
{{- end }}
