{{- if .Values.hmc.installTemplates }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .Values.hmc.motel.repo.name }}
  namespace: hmc-system
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  url: {{ .Values.hmc.motel.repo.url }}
{{- end }}
