apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-k8s-cluster-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-k8s-cluster-collector
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-k8s-cluster-collector
  namespace: {{ .Release.Namespace }}
