{{- if .Values.collectors.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-k8s-cluster
  namespace: {{ .Release.Namespace }}
spec:
  mode: deployment
  serviceAccount: "{{ .Release.Name }}-k8s-cluster-collector"
  config:
    receivers:
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
          - storage
        auth_type: serviceAccount
        collection_interval: 10s
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - NetworkUnavailable
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: pods
            mode: pull
            label_selector: environment in (production),tier in (frontend)
            field_selector: status.phase=Running
            interval: 1m
          - exclude_watch_type:
              - DELETED
            group: events.k8s.io
            mode: watch
            name: events

    processors:
      batch: {}

    exporters:
      debug: {}
      prometheusremotewrite:
        endpoint: {{ .Values.motel.metrics_endpoint }}
        tls:
          insecure: true
        auth:
          authenticator: basicauth/client
      otlphttp:
        auth:
          authenticator: basicauth/client
        logs_endpoint: {{ .Values.motel.logs_endpoint }}

    extensions:
      basicauth/client:
        client_auth:
          username: motel
          password: motel

    service:
      extensions:
        - basicauth/client
      pipelines:
        logs:
          exporters:
            - otlphttp
            - debug
          processors:
            - batch
          receivers:
            - k8sobjects
        metrics:
          exporters:
            - prometheusremotewrite
          processors:
            - batch
          receivers:
            - k8s_cluster
{{- end }}
