apiVersion: v2
name: motel-collector
description: A Helm chart that deploys OpenTelemetryCollector
version: 0.0.1
appVersion: "1.0"
dependencies:
  - name: prometheus-operator-crds
    version: "15.0.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-operator-crds.enabled
