{{- if .Values.hmc.installTemplates }}
apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: cert-manager
  namespace: hmc-system
spec:
  helm:
    chartRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: cert-manager
      namespace: hmc-system
  providers: []
{{- end }}
